%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/sgillen/Desktop/chai3d-3.2.0/bin/mac-undefined_arch/CursorPosition.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/14 16:08:23

%% Initialize variables.
filename = '/Users/sgillen/Desktop/chai3d-3.2.0/bin/mac-undefined_arch/CursorPosition.csv';
delimiter = ',';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
px = dataArray{:, 1};
py = dataArray{:, 2};
pz = dataArray{:, 3};
fx = dataArray{:, 4};
fy = dataArray{:, 5};
fz = dataArray{:, 6};
t = dataArray{:, 7};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;